name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # run the CI workflow at 6:00am UTC every Monday
    - cron: '0 6 * * MON'

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    timeout-minutes: 10
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php_version: ["8.0", "8.1", "8.2"]
        experimental: [false]

    steps:
    - name: Check out repository code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        fetch-depth: 0

    - name: Start up containers
      run: cd tests; ./init_containers.sh
    
    - name: Cache Composer dependencies
      uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
      with:
        path: |
          /tmp/composer-cache
          vendor
          components
        key: ${{ runner.os }}-php${{ matrix.php_version}}-skosmos3-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php${{ matrix.php_version}}-skosmos3-

    - name: Install Composer dependencies
      uses: php-actions/composer@8a65f0d3c6a1d17ca4800491a40b5756a4c164f3 # v6.1.2
      with:
        php_version: ${{ matrix.php_version }}
        php_extensions: intl xsl pcov

    - name: Install Node
      uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
      with:
        node-version: 16.x

    - name: Install JavaScript dependencies
      run: npm install

    - name: Check PHP code style
      run: ./vendor/bin/php-cs-fixer fix src --diff --dry-run

    - name: Check JavaScript code style
      run: cd resource/js; npx standard *.js

    - name: Run PHPUnit tests
      uses: php-actions/phpunit@8b81f7e713aba7ca15632bad78c56635ff327104 # v3.0.3
      env:
        LANGUAGE: fr
      with:
        version: 9.5
        php_version: ${{ matrix.php_version }}
        php_extensions: intl xsl pcov
        memory_limit: 512M
        configuration: phpunit.xml

    - name: Publish code coverage to Code Climate
      uses: paambaati/codeclimate-action@a1831d7162ea1fbc612ffe5fb3b90278b7999d59 # v5.0.0
      env:
        CC_TEST_REPORTER_ID: fb98170a5c7ea9cc2bbab19ff26268335e6a11a4f8267ca935e5e8ff4624886c
      with:
        prefix: /app

    - name: Publish code coverage to Codecov
      uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3.1.6

  cypress-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        fetch-depth: 0

    - name: Start up containers
      run: cd tests; ./init_containers.sh

    - name: Install Node
      uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
      with:
        node-version: 16.x

    - name: Install JavaScript dependencies
      run: npm install

    - name: Run Cypress tests
      run: npx cypress run
